---
".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true
Gemfile:
  required:
    ':system_tests':
      - gem: 'nokogiri'
        platforms: ruby
Rakefile:
  default_disabled_lint_checks:
    - relative
    - parameter_types
    - parameter_documentation
    - documentation
    - 140chars
spec/default_facts.yml:
  unmanaged: true
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.github/workflows/pr_test.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/spec.yml:
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
.travis.yml:
  delete: true
